version: '3.8'

services:
  # MariaDB Service
  mariadb-contact-form:
    image: mariadb:latest
    container_name: mariadb-contact-form
    restart: on-failure
    env_file: 
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb-contact-form-data:/var/lib/mysql
    networks:
      - contact-form-network-database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s


  # PHPMyAdmin Service
  phpmyadmin-contact-form:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-contact-form
    restart: on-failure
    env_file:
      - .env
    environment:
      - PMA_HOST=mariadb-contact-form
      - PMA_PORT=${CONT_MARIADB_PORT}
    ports:
      - "${HOST_PHPMYADMIN_PORT}:${CONT_PHPMYADMIN_PORT}"
    depends_on:
      mariadb-contact-form:
        condition: service_healthy
    networks:
      - contact-form-network-database

  # API Contact Form Service
  api-contact-form:
    build: .
    image: api-contact-form:1.0.0
    container_name: api-contact-form
    restart: on-failure
    depends_on:
      mariadb-contact-form:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${HOST_API_PORT}:${CONT_API_PORT}"
    environment:
      - DB_HOST=mariadb-contact-form
      - DB_PORT=${CONT_MARIADB_PORT}
    networks:
      - contact-form-network-database

volumes:
  mariadb-contact-form-data:

networks:
  contact-form-network-database:
    driver: bridge
